# API Research (r34)

This notebook explores the data structure returned by the API.

In [2]:
import requests
import pandas as pd
import json
from dotenv import load_dotenv
import os
load_dotenv()
import xml.etree.ElementTree as ET

import numpy as np
import matplotlib.pyplot as plt

Let's find how much tags are there. Each we have to get

# Dataset Formation and Cleanup

In [3]:
# Commented so I will not run it by mistake

# def check_page_exists(page):
#     """Checks if a page exists for a given ID using the Rule34 API."""
#     credentials = os.getenv('R34_ACCESS_CREDENTIALS')
#     url = f"https://api.rule34.xxx/index.php?page=dapi&s=tag&q=index&pid={page}&limit=1000"
#     try:
#         response = requests.get(f"{url}{credentials}", timeout=10)
#         root = ET.fromstring(response.content)
#         return len(root.findall('tag')) > 0
#     except Exception:
#         return False


# def find_total_tag_pages(low=1000, high=3000):
#     """Performs a binary search to find the highest valid tag ID."""
#     result = low
#     while low <= high:
#         mid = (low + high) // 2
#         print(f"Probing ID: {mid}...", end="\r")
#         if check_page_exists(mid):
#             result = mid
#             low = mid + 1
#         else:
#             high = mid - 1
#     return result

# total_tag_pages = find_total_tag_pages()
# print(f"\nApproximate total tags (highest ID): {total_tag_pages}")

# df = pd.DataFrame()
# credentials = os.getenv('R34_ACCESS_CREDENTIALS')
# for i in range(total_tag_pages+1):
#     try:
#         if i in pd.read_csv('../data/r34data/rule34_tags.csv', usecols=['page'])['page'].values:
#             print('skipped',i)
#             continue
#     except:
#         pass
#     url = f"https://api.rule34.xxx/index.php?page=dapi&s=tag&q=index&pid={i}&limit=1000"
#     response = requests.get(f"{url}{credentials}", timeout=100)
#     df = pd.read_xml(response.text)
#     df['page'] = i
#     if i == 0:
#         df.to_csv('../data/r34data/rule34_tags.csv', mode='w', index=False, header=True)
#     else:
#         df.to_csv('../data/r34data/rule34_tags.csv', mode='a', index=False, header=False)

Let's get data from file

In [11]:
df = pd.read_csv('../data/r34data/rule34_tags.csv')

# Creation of datasets for graphs

1. Which tag has the most posts
2. Which tag type is the most prevalent
3. Which character has the most posts
4. which artist has the most posts
5. which general tag has the most posts
6. which copyright has the most posts
7. Which metadata has the most posts
8. Linguistic analysis of tags
9. Are tags more often Ambiguous or not?

In [38]:
# 1. Tags with the most posts dataset
df_most_posts = df.sort_values(by='count', ascending=False).head(50)
df_most_posts

             type    count                 name  ambiguous       id  page
1464613   General  9637058               female       True      945  1503
1464535   General  7477148              breasts      False        5  1503
1464608   General  6047841                 male      False     1150  1503
1464597   General  4974863                penis       True       13  1503
1464200   General  4553421               1girls      False   798641  1503
756437    General  4379044             \breasts      False   189052   756
1464591   General  4018596              nipples      False       11  1503
1464484   General  3712806                 solo       True      108  1503
1464249   General  3693539                pussy      False       62  1503
1464256   General  3535272                  ass      False      164  1503
1464575   General  3435734                 nude       True      141  1503
1464594   General  3208465                blush      False        3  1503
1464523   General  3179910          big_breasts      False      942  1503
1464603   General  2805736               anthro      False    27692  1503
1464501   General  2624966                  sex      False       63  1503
1464196   General  2583756                 1boy       True     4739  1503
1464540   General  2479143                  cum       True       31  1503
1464516   General  2449510    looking_at_viewer      False     2694  1503
1464550  Metadata  2430273         ai_generated      False  1410377  1503
1464495   General  2399844            long_hair      False       37  1503
1464618  Metadata  2381369               hi_res       True    91626  1503
1464592   General  2218138                balls       True     1432  1503
1464536   General  2207248        large_breasts       True       10  1503
1464563   General  2185244         thick_thighs      False      374  1503
172989    General  2130017         \big_breasts      False  1077550   172
654773    General  2119218


anthro      False  2503903   654
1464510   General  2095197               mammal       True    92506  1503
1464216  Metadata  2024683                tagme      False      660  1503
1463449   General  1946927          female_only      False   251655  1502
1464424   General  1921034         huge_breasts      False      238  1503
1464537   General  1786214           open_mouth      False       12  1503
504019    General  1777973

cum      False  2110920   504
1464590   General  1660540                smile      False      255  1503
1464614   General  1626360             genitals      False    30392  1503
1464416   General  1588750              big_ass       True     1430  1503
1464607   General  1587401             erection      False     1149  1503
1464526   General  1580204             clothing      False    11701  1503
1464266   General  1552364            blue_eyes       True       97  1503
1464577   General  1414899          blonde_hair      False      145  1503
1464497   General  1352157           black_hair      False       49  1503
1464304   General  1345337  vaginal_penetration      False     3251  1503
1464600   General  1324945               tongue      False       25  1503
1464439   General  1318405                sweat      False       18  1503
1464369  Metadata  1313078                 text      False     2307  1503
1464547   General  1290058           light_skin      False    27458  1503
1464211  Metadata  1283522                   3d       True     8226  1503
1464379   General  1282599                 anus       True      144  1503
1464502   General  1259066            big_penis       True     4671  1503
1464417   General  1256528            wide_hips      False     1948  1503
1463376   General  1248058            male_only       True    27524  1502

In [30]:
# 1.1 Tags with the most posts dataset
len(df[df['count'] == 0])

28478

In [1]:
# 2. The most prevalent tag types
df[['type','count']].groupby('type').sum().sort_values(by='count', ascending=False).reset_index()

NameError: name 'df' is not defined

In [42]:
# 3. Which character has the most posts
df_most_posts_by_character = df[df['type']=='Character'].sort_values(by='count', ascending=False).head(50)
df_most_posts_by_character

              type   count                     name  ambiguous       id  page
1464599  Character  537620        pokemon_(species)      False  1009944  1503
1462920  Character  476110       original_character       True    28168  1501
1463406  Character  197500        pokémon_(species)      False   655160  1502
1464555  Character  109596                       oc      False   441179  1503
1453463  Character   77804              eeveelution      False   112218  1491
1464190  Character   76321            fan_character      False   116528  1503
1462950  Character   66130      original_characters      False   423898  1501
1458773  Character   58436        character_request      False      152  1497
1462694  Character   49165     generation_1_pokemon      False  1642017  1501
1461154  Character   47272         nami_(one_piece)      False  1491170  1499
1450077  Character   45533            tifa_lockhart      False      946  1487
1462856  Character   43491        legendary_pokemon      False   321812  1501
1459535  Character   43369           princess_peach      False     2824  1498
1456911  Character   42314        digimon_(species)      False   729871  1495
1463099  Character   40720     generation_4_pokemon      False  1642184  1501
1456716  Character   40017            rouge_the_bat      False    27926  1495
1459772  Character   37203            hyuuga_hinata       True     5266  1498
1463046  Character   36895                 amy_rose      False    27921  1501
1462303  Character   36801                robloxian      False   801275  1501
1463416  Character   36694                gardevoir      False      719  1502
1460686  Character   35955     loona_(helluva_boss)      False  1053002  1499
1460820  Character   34961            sakura_haruno      False    39097  1499
1460277  Character   34925               raven_(dc)       True   773987  1498
1460830  Character   34636                  lucario      False    27872  1499
1460927  Character   34271                  chun-li      False      522  1499
1457585  Character   33393           princess_zelda      False     3880  1496
1458926  Character   32646                  tsunade      False      358  1497
1453862  Character   32581           uzumaki_naruto      False     3680  1492
1461832  Character   32480       sonic_the_hedgehog      False    27913  1500
1462906  Character   32421             hatsune_miku      False      297  1501
1460319  Character   32343               samus_aran      False     6519  1498
1447973  Character   30823                  renamon      False    27445  1485
1456269  Character   30621                     d.va      False   449322  1494
1460496  Character   29337                     link      False     3878  1499
1458440  Character   28971               lara_croft      False    22608  1496
1455258  Character   28796   twilight_sparkle_(mlp)      False    91822  1493
1459639  Character   28324               nico_robin      False     2818  1498
1459563  Character   28201               widowmaker       True   382411  1498
1457567  Character   28128                     anon       True    16787  1495
1458064  Character   27307                    mercy       True    93132  1496
1459754  Character   27300           ochako_uraraka      False   535970  1498
1461712  Character   26933     generation_3_pokemon      False  1642351  1500
1459942  Character   25941  aether_(genshin_impact)       True  1060520  1498
1459767  Character   25830               android_18      False     2997  1498
1446685  Character   25481            tails_the_fox      False  1415155  1484
1461364  Character   25334     generation_2_pokemon      False  1642204  1499
1460777  Character   24832    makima_(chainsaw_man)      False   823774  1499
1464253  Character   24801     generation_5_pokemon      False  1642901  1503
1459526  Character   24686         fluttershy_(mlp)      False    91820  1498
1462185  Character   23681     generation_6_pokemon      False  1642923  1500

In [43]:
# 3.1 How much  characters has zero posts
len(df[(df['count'] == 0) & (df['type'] == 'Character')])

579

In [46]:
# 4. Which Artist has the most posts
df_most_posts_by_artist = df[df['type']=='Artist'].sort_values(by='count', ascending=False).head(50)
df_most_posts_by_artist

           type   count               name  ambiguous        id  page
1460433  Artist  194856     artist_request      False       163  1498
1464017  Artist   31810     unknown_artist      False     30615  1503
1460458  Artist   28486       electroworld      False   2429183  1499
1445888  Artist   16140            balecxi      False   2375758  1483
1454956  Artist   15864           palcomix      False    321076  1493
1454090  Artist   14678             bbmbbf      False     39572  1492
1449781  Artist   10551      jousneystudio      False   2348346  1487
1460039  Artist   10356          natsuyoru       True   2698055  1498
1420044  Artist   10227           foxenpai      False  44793853  1453
1379927  Artist    9805   julius_zimmerman       True    107109  1401
1460455  Artist    9525         skypassion      False  28339805  1499
1453485  Artist    9437   anonymous_artist      False     55392  1491
1437393  Artist    9238             anilvl      False   2661448  1473
1444084  Artist    8300  twistedscarlett60      False    398993  1481
1419368  Artist    7989         erophoenix      False  47677922  1452
1461010  Artist    7769           novalust       True  70272658  1499
1428009  Artist    7203        circle_anco      False      4747  1463
1434490  Artist    7153           grapesss      False   2103064  1470
1432779  Artist    6900         dibzprintz      False  19601641  1468
1457184  Artist    6870      cryptiacurves      False   1720068  1495
1445226  Artist    6852        kinkymation      False    606698  1482
1461152  Artist    6809          rule34lab      False   2498260  1499
1450471  Artist    6706    hagiwara_studio      False   1127539  1488
1359711  Artist    6698         darkeffect      False   1956255  1372
1444391  Artist    6384         hellsonger      False   2367041  1481
1378960  Artist    6103        dandon_fuga      False    475691  1400
1412684  Artist    5906      sinderellaart      False   2340628  1444
1462103  Artist    5861         progenarts      False   2292130  1500
1457195  Artist    5840            cally3d      False   1179327  1495
1359674  Artist    5639   boris_(noborhys)      False    353287  1372
1456818  Artist    5639       creamhorseai      False   2427975  1495
1436048  Artist    5599           neocoill       True    350004  1472
1423308  Artist    5562            nero100      False   1643215  1457
1370538  Artist    5552         bigtub7775      False  28123942  1388
1458466  Artist    5421            kexonik      False   2421696  1496
1460819  Artist    5372              maldo      False  95181239  1499
1463848  Artist    5358            r34arts      False   2380352  1502
1405030  Artist    5295     bythebrokenone      False   1002444  1434
1386185  Artist    5272       stevencarson      False    406315  1410
1430081  Artist    5272           ero-enzo      False    456537  1465
1454385  Artist    5238         scorpianpp      False   1976226  1492
1447841  Artist    5149           belliora      False  22935189  1485
1451518  Artist    5057            klexyai      False   2645143  1489
1399824  Artist    5043        deep_rising       True      6849  1428
1413186  Artist    5027   mobius_unleashed      False    340897  1445
1420991  Artist    5003         juanpiamvs      False   2642650  1454
1307048  Artist    4959         sakimichan       True    359336  1307
1411831  Artist    4785   sparrow_(artist)      False   1003050  1443
1431182  Artist    4780              ber00      False    460334  1466
1457408  Artist    4703        frosting.ai       True   2010005  1495

In [49]:
# 4.1 How much artists have 0 posts?
len(df[(df['count'] == 0) & (df['type'] == 'Artist')])

842

In [52]:
# 5. Which general tag has the most posts
df_most_posts_by_general = df[df['type']=='General'].sort_values(by='count', ascending=False).head(50)
df_most_posts_by_general

            type    count                 name  ambiguous       id  page
1464613  General  9637058               female       True      945  1503
1464535  General  7477148              breasts      False        5  1503
1464608  General  6047841                 male      False     1150  1503
1464597  General  4974863                penis       True       13  1503
1464200  General  4553421               1girls      False   798641  1503
756437   General  4379044             \breasts      False   189052   756
1464591  General  4018596              nipples      False       11  1503
1464484  General  3712806                 solo       True      108  1503
1464249  General  3693539                pussy      False       62  1503
1464256  General  3535272                  ass      False      164  1503
1464575  General  3435734                 nude       True      141  1503
1464594  General  3208465                blush      False        3  1503
1464523  General  3179910          big_breasts      False      942  1503
1464603  General  2805736               anthro      False    27692  1503
1464501  General  2624966                  sex      False       63  1503
1464196  General  2583756                 1boy       True     4739  1503
1464540  General  2479143                  cum       True       31  1503
1464516  General  2449510    looking_at_viewer      False     2694  1503
1464495  General  2399844            long_hair      False       37  1503
1464592  General  2218138                balls       True     1432  1503
1464536  General  2207248        large_breasts       True       10  1503
1464563  General  2185244         thick_thighs      False      374  1503
172989   General  2130017         \big_breasts      False  1077550   172
654773   General  2119218


anthro      False  2503903   654
1464510  General  2095197               mammal       True    92506  1503
1463449  General  1946927          female_only      False   251655  1502
1464424  General  1921034         huge_breasts      False      238  1503
1464537  General  1786214           open_mouth      False       12  1503
504019   General  1777973

cum      False  2110920   504
1464590  General  1660540                smile      False      255  1503
1464614  General  1626360             genitals      False    30392  1503
1464416  General  1588750              big_ass       True     1430  1503
1464607  General  1587401             erection      False     1149  1503
1464526  General  1580204             clothing      False    11701  1503
1464266  General  1552364            blue_eyes       True       97  1503
1464577  General  1414899          blonde_hair      False      145  1503
1464497  General  1352157           black_hair      False       49  1503
1464304  General  1345337  vaginal_penetration      False     3251  1503
1464600  General  1324945               tongue      False       25  1503
1464439  General  1318405                sweat      False       18  1503
1464547  General  1290058           light_skin      False    27458  1503
1464379  General  1282599                 anus       True      144  1503
1464502  General  1259066            big_penis       True     4671  1503
1464417  General  1256528            wide_hips      False     1948  1503
1463376  General  1248058            male_only       True    27524  1502
1464596  General  1240277                  duo      False   188172  1503
1464513  General  1229156                human       True    23934  1503
1464602  General  1226125                  fur      False     1565  1503
1464207  General  1206755               thighs      False      241  1503
1464377  General  1185189          penetration      False      617  1503

In [58]:
# 6. Which copyright has the most posts
df_most_posts_by_copyright = df[df['type']=='Copyright'].sort_values(by='count', ascending=False).head(50)
df_most_posts_by_copyright

,type,count,name,ambiguous,id,page
1464617,Copyright,1026250,nintendo,False,469,1503
1464615,Copyright,842643,pokemon,False,199,1503
1463788,Copyright,535791,original,False,61,1502
1462536,Copyright,266097,my_little_pony,False,38982,1501
1461641,Copyright,251602,disney,False,27981,1500
1464032,Copyright,227594,genshin_impact,True,1034398,1503
1464454,Copyright,220406,mythology,False,31040,1503
1462537,Copyright,208055,friendship_is_magic,False,85841,1501
1460814,Copyright,190465,naruto,False,354,1499
1463768,Copyright,189600,league_of_legends,True,27655,1502
1460923,Copyright,186567,sonic_(series),False,91712,1499
1460305,Copyright,179630,marvel,True,8851,1498
1460312,Copyright,162733,marvel_comics,False,90105,1498
1458889,Copyright,160507,dc_comics,False,8100,1497
1460278,Copyright,157934,dc,False,14975,1498
1459564,Copyright,154775,overwatch,False,217044,1498
1460799,Copyright,153547,my_hero_academia,False,518891,1499
1460385,Copyright,145028,final_fantasy,False,153,1498
1458098,Copyright,137080,fire_emblem,False,4111,1496
1462028,Copyright,135193,fate_(series),False,171331,1500
1463756,Copyright,132442,mario_(series),False,641591,1502
1460815,Copyright,131626,naruto_(series),False,742800,1499
1461131,Copyright,131166,one_piece,False,1106,1499
1461231,Copyright,127741,touhou,False,142,1499
1463055,Copyright,124254,sega,False,1145,1501
1464228,Copyright,124233,capcom,False,386,1503
1460361,Copyright,123272,dragon_ball,False,1363,1498
1463045,Copyright,119558,sonic_the_hedgehog_(series),False,885774,1501
1459556,Copyright,114709,blizzard_entertainment,False,269338,1498
1462545,Copyright,105813,hasbro,False,54230,1501
1461155,Copyright,105591,fortnite,True,635627,1499
1463557,Copyright,102720,world_of_warcraft,False,2747,1502
1464300,Copyright,99760,fate/grand_order,False,422886,1503
1460933,Copyright,93992,street_fighter,True,384,1499
1461634,Copyright,93212,cartoon_network,False,33161,1500
1464329,Copyright,91453,christmas,False,1586,1503
1463874,Copyright,91260,hololive,False,800122,1502
1456518,Copyright,89984,naruto_shippuden,False,106079,1494
1460497,Copyright,89485,the_legend_of_zelda,False,3881,1499
1463782,Copyright,88974,riot_games,False,237533,1502
1458750,Copyright,86628,resident_evil,False,4936,1497
1459886,Copyright,84571,five_nights_at_freddy's,False,370679,1498
1463342,Copyright,80462,bleach,False,2502,1502
1463556,Copyright,79624,warcraft,False,2746,1502
1460808,Copyright,71675,game_freak,False,394321,1499
1463632,Copyright,70561,blue_archive,True,1028315,1502
1457362,Copyright,69440,digimon,False,14283,1495
1463900,Copyright,69200,zenless_zone_zero,True,1536759,1502
1460386,Copyright,66922,final_fantasy_vii,False,154,1498
1459763,Copyright,64783,dragon_ball_z,False,1364,1498

In [54]:
# 6.1 Which copyright has 0 posts
len(df[(df['count'] == 0) & (df['type'] == 'Copyright')])

144

In [59]:
# 7. Which Metadata Tag has the most posts
df_most_posts_by_metadata = df[df['type']=='Metadata'].sort_values(by='count', ascending=False).head(50)
df_most_posts_by_metadata

,type,count,name,ambiguous,id,page
1464550,Metadata,2430273,ai_generated,False,1410377,1503
1464618,Metadata,2381369,hi_res,True,91626,1503
1464216,Metadata,2024683,tagme,False,660,1503
1464369,Metadata,1313078,text,False,2307,1503
1464211,Metadata,1283522,3d,True,8226,1503
1463932,Metadata,1232877,highres,False,8,1502
1463901,Metadata,1062267,censored,False,7,1502
1464611,Metadata,1030872,simple_background,False,663,1503
1464621,Metadata,865438,absurd_res,False,37103,1503
1464374,Metadata,837628,english_text,False,91716,1503
1464251,Metadata,772955,uncensored,False,67,1503
1460680,Metadata,647809,animated,True,27325,1499
1464512,Metadata,601195,digital_media_(artwork),False,389229,1503
1464341,Metadata,583312,dialogue,False,35956,1503
1460211,Metadata,509410,video_games,False,18483,1498
1460850,Metadata,432802,video,False,793856,1499
1463735,Metadata,431338,2d,False,34881,1502
1463604,Metadata,405271,monochrome,False,378,1502
1464257,Metadata,394382,comic,False,1012,1503
1464433,Metadata,361270,speech_bubble,False,1419,1503
1463969,Metadata,351573,high_resolution,True,317940,1502
1463945,Metadata,346493,artist_name,False,186471,1502
1463961,Metadata,342548,stable_diffusion,False,1645765,1502
1463948,Metadata,328535,watermark,False,1656,1502
1463885,Metadata,312084,absurdres,False,1579,1502
1463912,Metadata,283749,mosaic_censoring,False,213804,1502
1464011,Metadata,252148,2025,False,2406905,1503
1463953,Metadata,238017,patreon,False,374418,1502
1460623,Metadata,237998,sound,False,111367,1499
1463836,Metadata,204063,translation_request,False,27,1502
1463868,Metadata,202350,virtual_youtuber,False,564817,1502
1463222,Metadata,188639,color,False,7555,1502
1462327,Metadata,186301,3d_(artwork),False,451034,1501
1463209,Metadata,178674,2023,False,1447068,1502
1460854,Metadata,178485,2022,False,1399331,1499
1464145,Metadata,176629,self_upload,False,652979,1503
1459448,Metadata,172150,2024,False,2174925,1497
1460617,Metadata,164005,alternate_version_available,False,425070,1499
1462208,Metadata,163008,crossover,False,951,1500
1460943,Metadata,161027,japanese_text,False,91707,1499
1464154,Metadata,156153,sketch,False,1072,1503
1463880,Metadata,149186,bar_censor,False,339905,1502
1461013,Metadata,145639,rule_63,False,4014,1499
1462218,Metadata,143631,detailed_background,True,133262,1500
1463829,Metadata,141657,game_cg,False,684,1502
1458758,Metadata,136332,2021,False,1109416,1497
1461904,Metadata,134679,no_sound,False,395503,1500
1463938,Metadata,133508,high_quality,True,928569,1502
1463971,Metadata,131955,ai_assisted,False,1897466,1502
1463507,Metadata,131449,commission,False,68243,1502

In [68]:
temp_df

                       name    count       type                   word
0                  kogurein        2  Copyright             [kogurein]
1               noki_welkin        1  Character         [noki, welkin]
2               norita_mado        1  Character         [norita, mado]
3             kyrie_(quilt)        1  Character         [kyrie, quilt]
4                  kyomachi        1     Artist             [kyomachi]
...                     ...      ...        ...                    ...
1464618              hi_res  2381369   Metadata              [hi, res]
1464619           white_fur   379746    General           [white, fur]
1464620  humanoid_genitalia   280124    General  [humanoid, genitalia]
1464621          absurd_res   865438   Metadata          [absurd, res]
1464622            red_body   107362    General            [red, body]

[1464623 rows x 4 columns]

In [ ]:
#8. linguistic analysis
import re

def extract_words(name):
    if pd.isna(name):
        return []
    # Split by non-alphanumeric characters (keeps only words and numbers)
    # This splits on underscores, parentheses, spaces, etc.
    words = re.split(r'[^a-zA-Z0-9]+', str(name))
    # Filter out empty strings and convert to lowercase
    return [w.lower() for w in words if w]

# Create a temporary dataframe for processing
# We use .copy() to avoid SettingWithCopyWarning
temp_df = df[['name', 'count','type']].copy()
temp_df['word'] = temp_df['name'].apply(extract_words)

# Explode the list of words so each word gets its own row
exploded = temp_df.explode('word')

# Group by word and calculate statistics
word_stats = exploded.groupby(['word','type']).agg(
    tag_count=('name', 'nunique'),      # Count how many tags contain this word
    posts_count=('count', 'sum')      # Sum of posts for tags containing this word
).reset_index()

# Sort by tag_count to find the most prevalent words in names
word_stats = word_stats.sort_values(by='tag_count', ascending=False)

# Display the top 20 words
word_stats.head(20)

             word       type  tag_count  posts_count
616248          r    General      28790        13622
55312      artist     Artist      17105       606249
562160         on    General      13888      7047004
764339        the    General      13471       167236
510010          n    General       9586         7973
764337        the  Character       9485       551906
55315      artist    General       9004        31230
335659         in    General       7989      2580544
129238  character    General       7907       214848
129236  character  Character       6176       769188
557736         of    General       6151       311207
655603          s    General       4844       207075
583215      penis    General       4822     11948060
296181       hair    General       4793     18329139
237899     female    General       4493     23419488
454736       male    General       4088     15631107
159659        cum    General       3994      9987888
764338        the  Copyright       3960      1123378
557734         of  Character       3858       233569
59495         ass    General       3844     10494068

In [87]:
word_stats[word_stats['type'] == 'Copyright'].sort_values(by='tag_count', ascending=False).head(50)

            word       type  tag_count  posts_count
764338       the  Copyright       3960      1123378
539937        no  Copyright       2875       418837
557735        of  Copyright       2139       882062
655602         s  Copyright       1150       391895
677899    series  Copyright       1012      1385813
40344        and  Copyright        994       155430
5351           2  Copyright        944       360224
776986        to  Copyright        860        89508
530773        ni  Copyright        709        85272
266102      game  Copyright        688       189212
15097          a  Copyright        655        54295
823544        wa  Copyright        536        98862
335658        in  Copyright        494        64728
263728        ga  Copyright        434        52837
147145     comic  Copyright        388         8854
7713           3  Copyright        380       155260
174080        de  Copyright        372        20307
839363     world  Copyright        334       174210
508270        my  Copyright        331       466227
841833         x  Copyright        315       116318
439397      love  Copyright        288        63346
662173       san  Copyright        273        41585
510613        na  Copyright        260        13402
532237     night  Copyright        257        93747
739757     super  Copyright        253       146530
147639   company  Copyright        247        31975
692616    shoujo  Copyright        246        37391
836688        wo  Copyright        244        67989
276711      girl  Copyright        241        26598
727659      star  Copyright        241       178605
198001    dragon  Copyright        232       376998
605071  princess  Copyright        222        75964
264993    gakuen  Copyright        216        10131
328101         i  Copyright        210        13183
428420      life  Copyright        205        43847
242203      film  Copyright        205        54537
555017         o  Copyright        205        12961
276865     girls  Copyright        200        84223
128349      chan  Copyright        199        24229
616247         r  Copyright        192         8040
94696       blue  Copyright        190       112209
456396       man  Copyright        185       209462
528377       new  Copyright        184        45467
372865    kanojo  Copyright        184        19914
250204       for  Copyright        182        16196
143381      club  Copyright        178        44495
98095       boku  Copyright        177        56756
597934   pokemon  Copyright        174      1234498
822129        vs  Copyright        173        42977
566291       ore  Copyright        169        11157

In [88]:
word_stats[word_stats['type'] == 'Copyright'].sort_values(by='posts_count', ascending=False).head(50)

              word       type  tag_count  posts_count
677899      series  Copyright       1012      1385813
597934     pokemon  Copyright        174      1234498
764338         the  Copyright       3960      1123378
535482    nintendo  Copyright         19      1034296
557735          of  Copyright       2139       882062
566877    original  Copyright         18       538883
516703      naruto  Copyright         20       504620
508270          my  Copyright        331       466227
539937          no  Copyright       2875       418837
462226      marvel  Copyright         49       398703
715946       sonic  Copyright        120       398431
655602           s  Copyright       1150       391895
147207      comics  Copyright        117       382406
198001      dragon  Copyright        232       376998
188608      disney  Copyright         44       375984
233762     fantasy  Copyright        134       361919
5351             2  Copyright        944       360224
242423       final  Copyright         94       332210
173623          dc  Copyright         19       325925
243135        fire  Copyright         68       322782
217077      emblem  Copyright         33       313847
509723   mythology  Copyright         67       312017
432904      little  Copyright        169       293294
235007        fate  Copyright         51       278096
599849        pony  Copyright         24       272377
421958     legends  Copyright         70       268367
317967    hololive  Copyright         37       268325
72851         ball  Copyright         58       262761
335025      impact  Copyright         20       237132
342462          is  Copyright        148       234817
309722        hero  Copyright        112       231486
272053     genshin  Copyright          4       227618
420672      league  Copyright         80       222911
571415   overwatch  Copyright          8       221823
451327       magic  Copyright        107       219008
460270       mario  Copyright        136       218442
17621     academia  Copyright         20       214293
255391  friendship  Copyright          8       212301
227595        evil  Copyright         75       211079
456396         man  Copyright        185       209462
634135    resident  Copyright         39       196221
266102        game  Copyright        688       189212
826128    warcraft  Copyright          4       182712
727659        star  Copyright        241       178605
839363       world  Copyright        334       174210
562390         one  Copyright        124       172002
306373    hedgehog  Copyright         23       167500
40344          and  Copyright        994       155430
7713             3  Copyright        380       155260
241789     fighter  Copyright         66       153575

In [91]:
df_most_posts_by_character['name'].tolist()

['pokemon_(species)',
 'original_character',
 'pokémon_(species)',
 'oc',
 'eeveelution',
 'fan_character',
 'original_characters',
 'character_request',
 'generation_1_pokemon',
 'nami_(one_piece)',
 'tifa_lockhart',
 'legendary_pokemon',
 'princess_peach',
 'digimon_(species)',
 'generation_4_pokemon',
 'rouge_the_bat',
 'hyuuga_hinata',
 'amy_rose',
 'robloxian',
 'gardevoir',
 'loona_(helluva_boss)',
 'sakura_haruno',
 'raven_(dc)',
 'lucario',
 'chun-li',
 'princess_zelda',
 'tsunade',
 'uzumaki_naruto',
 'sonic_the_hedgehog',
 'hatsune_miku',
 'samus_aran',
 'renamon',
 'd.va',
 'link',
 'lara_croft',
 'twilight_sparkle_(mlp)',
 'nico_robin',
 'widowmaker',
 'anon',
 'mercy',
 'ochako_uraraka',
 'generation_3_pokemon',
 'aether_(genshin_impact)',
 'android_18',
 'tails_the_fox',
 'generation_2_pokemon',
 'makima_(chainsaw_man)',
 'generation_5_pokemon',
 'fluttershy_(mlp)',
 'generation_6_pokemon']